### ISSUE TITLE
Container options panel not usable with different DPI

### ISSUE THREAD

**Issue by Magneticdud** [stax76/staxrip#214]
I have a 4k screen so I had to increase screen DPI

Windows 10 creators update, staxrip 1.3.7.0 was working fine, in staxrip 1.5.0.0 the container options panel is not usable

tried to disable DPI scaling in windows, but nothing happened

screenshot:

![dpi](https://user-images.githubusercontent.com/2940598/27856809-97c5670e-616f-11e7-9b6a-8f4fa0efcda7.png)

**Comment by stax76** [comment]
I believe this was fixed, could you please try the newest test build?

https://github.com/stax76/staxrip/blob/master/md/test-build.md

How much DPI are you using (I use 288 with 4K screen)?

**Comment by Magneticdud** [comment]
Yes, it has been fixed in the latest test build
DPI... I am using 150% zoom, that means... 144 dpi?

anyway it works, thanks

ps: the onedrive link is broken

**Comment by stax76** [comment]
Yes, 150% Zoom equals 144 DPI, can you please try the onedrive link again? I just tried it and it worked.

**Comment by Magneticdud** [comment]
Still doesn't work, if i try in incognito mode it forces me to login - looks like a permission problem

**Comment by stax76** [comment]
I guess it works only with login, it's OK as long one of the two works otherwise I can try dropbox in the future.
